name: CI FitWave Docker

# Déclenche l'action à chaque "push" sur la branche main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère ton code HTML/CSS/Docker sur le serveur GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Tente de construire l'image Docker (Test de validité)
      - name: Build Docker image
        run: docker build -t fitwave-app .