name: CI FitWave Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fitwave-app .
        
      - name: Test Docker image
        run: docker run --name test-container -d -p 8080:80 fitwave-app