name: CI — Validation FitWave

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-structure:
    name: 📁 Vérification des fichiers
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔎 Vérifier les fichiers requis
        run: |
          REQUIRED_FILES=("index.html" "style.css" "Dockerfile")
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ -f "$FILE" ]; then
              echo "✅ $FILE trouvé"
            else
              echo "❌ $FILE MANQUANT"
              exit 1
            fi
          done

  docker-build:
    name: 🐳 Test Docker
    runs-on: ubuntu-latest
    needs: check-structure
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
      - name: 🛠️ Build de l'image
        run: docker build -t fitwave-app .