name: CI FitWave

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. TEST (obligatoire)
      - name: Vérifier fichier HTML
        run: |
          if [ ! -f index.html ]; then
            echo "Erreur : index.html manquant"
            exit 1
          fi

      # 4. BUILD DOCKER
      - name: Build Docker image
        run: docker build -t fitwave .