name: CI FitWave

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. TEST normal
      - name: Vérifier HTML
        run: |
          if [ ! -f index.html ]; then
            echo "Erreur : fichier manquant"
            exit 1
          fi

      # ❌ 3. TEST ERREUR (AJOUTE ICI)
      - name: Test erreur
        run: exit 1

      # 4. BUILD DOCKER
      - name: Build Docker
        run: docker build -t fitwave .